demo:
  data:
    elasticsearch:
    # es集群名称
      cluster-name: elasticsearch
    # es集群节点，多个逗号分隔 localhost:9200,localhost:9400
      cluster-nodes: localhost:9200
    # 设置创建index时，默认的分片规则
      index:
        number-of-shards: 3
        number-of-replicas: 2
    # 设置连接es的用户名和密码
      account:
        username: elastic
        password: 123456
